In [1]:
import torch

In [2]:
torch.tensor(12)

tensor(12)

In [3]:
torch.randn(12)

tensor([-1.8341, -0.8542, -1.5095, -0.6045, -0.0305,  1.2706,  0.8605,  0.4373,
         0.8818, -0.2097,  0.0770,  1.6483])

In [4]:
torch.randn((3,4))

tensor([[ 1.6769, -1.5603, -2.1569, -0.4373],
        [ 1.2141, -0.2285, -0.7524,  2.1166],
        [ 0.5180,  0.2211,  0.7288, -0.3417]])

In [5]:
torch.randn(3,4)[0][0].item()

1.098828673362732

In [6]:
torch.randn(3,4).ndim

2

In [7]:
random_tensor = torch.randn(2,3,4,5)

In [8]:
random_tensor.shape

torch.Size([2, 3, 4, 5])

In [9]:
random_tensor.ndim

4

In [10]:
random_tensor[0]   ## first dimension of the tensor

tensor([[[ 1.1213, -0.0385, -0.6374,  0.4432,  0.3222],
         [ 0.6590, -0.6812, -0.7578,  0.4252,  0.9463],
         [-1.0805,  0.5885, -0.2731, -1.0458,  0.7455],
         [ 0.1154,  0.4260,  1.7849, -0.7642,  0.2733]],

        [[-0.5482,  1.1751, -1.3984,  2.7013, -0.1737],
         [ 0.0766,  0.4119,  0.7056,  0.6006, -0.8570],
         [-0.9761, -0.1835,  1.1577,  0.2799, -0.1719],
         [ 0.1785, -2.6530,  0.3400, -0.9734,  0.2604]],

        [[ 0.0112, -0.3116, -1.2758, -1.9917,  1.5787],
         [ 0.1177,  1.2112, -1.2648,  0.5989,  0.8205],
         [ 0.4259,  1.8492, -1.7321, -1.4087,  0.1066],
         [-0.0682,  0.4063, -0.6809, -1.7241, -1.0805]]])

In [11]:
## randn gives tensor of noraml distribution
## rand gives tennsors randomly

In [12]:
torch.rand(3,4,5)

tensor([[[0.8723, 0.4058, 0.2284, 0.6539, 0.3502],
         [0.4983, 0.4444, 0.6165, 0.5193, 0.9231],
         [0.2696, 0.7780, 0.2771, 0.8811, 0.1520],
         [0.1384, 0.6178, 0.1023, 0.0410, 0.7411]],

        [[0.5485, 0.2067, 0.2564, 0.6851, 0.2469],
         [0.1303, 0.1982, 0.0241, 0.1687, 0.5943],
         [0.4909, 0.2776, 0.6586, 0.6972, 0.1181],
         [0.2650, 0.3434, 0.9958, 0.7700, 0.0611]],

        [[0.6151, 0.3749, 0.9689, 0.4287, 0.2976],
         [0.1760, 0.5480, 0.1533, 0.9371, 0.9343],
         [0.7070, 0.5903, 0.7190, 0.5811, 0.0949],
         [0.9608, 0.5968, 0.0750, 0.2156, 0.4690]]])

In [13]:
zeros = torch.zeros(2,3,4)  ## used for masking tensors, where you can make the tensor value 0.

In [14]:
ones = torch.ones(2,3,4)

In [15]:
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
tensor_range = torch.arange(0,12,2)  

In [18]:
zero_like_tensor = torch.zeros_like(random_tensor[0][1][1])

In [19]:
zero_like_tensor

tensor([0., 0., 0., 0., 0.])

In [20]:
random_tensor = torch.rand(2,3,4,5)

In [21]:
random_tensor

tensor([[[[0.8985, 0.5852, 0.4663, 0.9655, 0.4617],
          [0.1373, 0.9886, 0.9402, 0.0429, 0.5576],
          [0.5749, 0.7635, 0.3423, 0.1111, 0.0082],
          [0.0392, 0.6526, 0.1662, 0.7310, 0.1001]],

         [[0.8915, 0.0240, 0.0321, 0.3962, 0.0828],
          [0.5234, 0.4931, 0.6297, 0.4392, 0.4592],
          [0.4683, 0.8491, 0.3741, 0.0036, 0.5435],
          [0.0205, 0.5314, 0.1701, 0.6546, 0.0066]],

         [[0.9470, 0.8113, 0.9061, 0.4981, 0.3548],
          [0.8802, 0.7181, 0.3038, 0.2606, 0.0341],
          [0.8755, 0.7392, 0.2514, 0.5449, 0.1221],
          [0.6168, 0.5166, 0.1215, 0.7416, 0.2506]]],


        [[[0.5473, 0.6167, 0.2219, 0.5257, 0.8499],
          [0.6447, 0.4171, 0.6677, 0.4876, 0.9213],
          [0.8541, 0.2041, 0.3766, 0.8093, 0.9943],
          [0.2075, 0.2666, 0.5806, 0.9645, 0.6015]],

         [[0.1845, 0.2764, 0.4797, 0.7421, 0.2016],
          [0.8949, 0.4603, 0.1967, 0.4383, 0.7196],
          [0.5339, 0.3922, 0.2037, 0.0359, 0.1115],
  

In [22]:
random_tensor[0] = torch.zeros_like(random_tensor[0])

In [23]:
random_tensor

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.5473, 0.6167, 0.2219, 0.5257, 0.8499],
          [0.6447, 0.4171, 0.6677, 0.4876, 0.9213],
          [0.8541, 0.2041, 0.3766, 0.8093, 0.9943],
          [0.2075, 0.2666, 0.5806, 0.9645, 0.6015]],

         [[0.1845, 0.2764, 0.4797, 0.7421, 0.2016],
          [0.8949, 0.4603, 0.1967, 0.4383, 0.7196],
          [0.5339, 0.3922, 0.2037, 0.0359, 0.1115],
  

In [24]:
int_tensor = torch.tensor([1,2,3,4], dtype=torch.int32, device='cuda', requires_grad = True) ## int can't have gradients

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [25]:
float_tensor = torch.tensor([1,2,3,4], dtype=torch.float64, device='cuda', requires_grad = True) ## int can't have gradients

In [26]:
float_tensor

tensor([1., 2., 3., 4.], device='cuda:0', dtype=torch.float64,
       requires_grad=True)

In [27]:
## MATRIX MULTIPLICATION

In [28]:
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[0.8690, 1.0396, 1.0442, 0.3544],
        [0.9751, 1.1253, 1.4362, 0.7406]])

In [29]:
torch.mm(torch.rand(2,3), torch.rand(3,4))

tensor([[1.2608, 1.1841, 1.0449, 0.7841],
        [0.5697, 0.6683, 0.6777, 0.4828]])

In [30]:
torch.matmul(torch.rand(2,3), torch.rand(2,3).T)

tensor([[1.2105, 1.3794],
        [0.9950, 0.9751]])

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [33]:
a, b

(tensor([[0.3734, 0.4094, 0.5000],
         [0.1114, 0.5351, 0.2372]]),
 tensor([[0.5803, 0.1562, 0.8553],
         [0.6037, 0.2760, 0.5807]]))

In [35]:
torch.matmul(a, b.T)

tensor([[0.7083, 0.6287],
        [0.3511, 0.3527]])

In [41]:
x = torch.arange(0,100,1)

In [44]:
x.type(torch.float32).mean()

tensor(49.5000)

In [46]:
x.max(), x.min()

(tensor(99), tensor(0))

In [47]:
x.shu
x.argmax(), x.argmin()

(tensor(99), tensor(0))

In [64]:
x = torch.arange(0. ,10)
y = torch.arange(12, 22)

In [50]:
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
x.shape

torch.Size([10])

In [61]:
x = x.reshape(2,5)

In [55]:
x

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [65]:
torch.stack((x, y), dim=1)

tensor([[ 0., 12.],
        [ 1., 13.],
        [ 2., 14.],
        [ 3., 15.],
        [ 4., 16.],
        [ 5., 17.],
        [ 6., 18.],
        [ 7., 19.],
        [ 8., 20.],
        [ 9., 21.]])

In [66]:
torch.stack((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]])

In [78]:
x = x.unsqueeze(dim=1)

In [79]:
x.unsqueeze(dim=0)

tensor([[[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [80]:
x

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [84]:
torch.permute(x, (1,0))

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [85]:
x.shape

torch.Size([10, 1])

In [86]:
x

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [96]:
import numpy as np
array = np.arange(1,10, dtype=np.float32)

In [97]:
tensor = torch.from_numpy(array)
array.dtype, tensor.dtype

(dtype('float32'), torch.float32)

In [98]:
torch.cuda.is_available()

True